#services:
#  db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'sportinformation'
#      MYSQL_USER: 'dev'
#      MYSQL_PASSWORD: 'password'
#      MYSQL_ROOT_PASSWORD: 'password'
#    ports:
#      - 3306:3306
#    expose:
#      - 3306
#
